#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubyboy'
require 'optparse'

options = { speed: 1.0 }
begin
  OptionParser.new do |opts|
    opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} [options] ROM_PATH"

    opts.on('--speed SPEED', Float, 'Initial emulation speed multiplier (default: 1.0)') do |speed|
      options[:speed] = speed
    end

    opts.on('-h', '--help', 'Displays this help') do
      puts opts
      exit
    end
  end.parse!

  raise OptionParser::InvalidArgument, '--speed must be 1.0 or greater' unless options[:speed] >= 1.0
rescue OptionParser::ParseError => e
  puts e.message
  puts "Usage: #{File.basename($PROGRAM_NAME)} [options] ROM_PATH"
  exit 1
end

rom_path = ARGV.shift || 'lib/roms/tobu.gb'

puts "Ruby: #{RUBY_VERSION}"
if defined?(RubyVM::YJIT)
  puts "YJIT: #{RubyVM::YJIT.enabled?}"
else
  puts 'YJIT is not available in this environment.'
end
puts "Speed: #{options[:speed]}x"
puts 'Speed keys: F1=1x, F2=2x, F3=4x, F4=8x'

Rubyboy::Emulator.new(rom_path, speed: options[:speed]).start
